#!/bin/sh
### BEGIN INIT INFO
# Provides:          monitowl-agent
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: MonitOwl.com  Agent
### END INIT INFO

# Author: MonitOwl Team <office@monitowl.com>
#
DESC="MonitOwl agent service"
DAEMON="/opt/monitowl/monitowl-agent"
DAEMON_ARGS="-c /opt/monitowl/agentconfig.ini"
PIDFILE=/var/run/monitowl-agent.pid

# Functions
do_start()
{
    start-stop-daemon -v -d /opt/monitowl/ --start --oknodo --background --make-pidfile --no-close --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS  >> /opt/monitowl/agent.log 2>&1
    RETVAL=$?
}
do_stop()
{
    start-stop-daemon --stop --oknodo --pidfile $PIDFILE --retry 5
    RETVAL=$?
}



case "$1" in
  start)
        do_start
        ;;
  stop)
        do_stop
        ;;
esac
exit 0
